#!/bin/sh

set -e

NAME=Debian
MAP=`dirname $0`/$NAME.map
VARS=`dirname $0`/$NAME.fd

TAP=tap0
DRIVE=/dev/zvol/storage/VMs/bhyve/$NAME
ISO=/home/anton/Downloads/debian-13.2.0-amd64-netinst.iso

CPU=`nproc`
RAM=8192

vm-init

#grub-bhyve \
#	-m $MAP \
#	-M $RAM \
#	-r hd0 \
#	$NAME

bhyve \
	-A -D -H -P -u -w \
	-c $CPU \
	-m "$RAM"M \
	-s 0,hostbridge \
	-s 1,lpc \
	-s 2,virtio-net,$TAP \
	-s 3,virtio-blk,$DRIVE \
	-s 4,ahci-cd,$ISO \
	-s 5,hda,play=/dev/dsp,rec=/dev/dsp \
	-l com1,stdio \
	-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd,$VARS \
	$NAME

vm-destroy $NAME
