#!/bin/sh

set -e

NAME=FreeBSD

TAP=tap0
DRIVE=/dev/zvol/storage/VMs/bhyve/$NAME
ISO=/home/anton/Downloads/FreeBSD-15.0-RELEASE-amd64-bootonly.iso

CPU=`nproc`
RAM=2G

vm-init

bhyveload \
	-c stdio \
	-m $RAM \
	-d $DRIVE \
	$NAME

bhyve \
	-A -D -H -P -u -w \
	-c $CPU \
	-m $RAM \
	-s 0,hostbridge \
	-s 1,lpc \
	-s 2,virtio-net,$TAP \
	-s 3,virtio-blk,$DRIVE \
	-s 4,ahci-cd,$ISO \
	-l com1,stdio \
	$NAME

vm-destroy $NAME
