#!/bin/sh

GOFA=`go env GOPATH`/src/github.com/anton2920/gofa

while test "$#" -gt "0"; do
	if test -d "$GOFA/$1"; then
		find $GOFA/$1 -type f | grep -v '\.git' | grep -v README
	elif test -f "$GOFA/$1"; then
		echo $GOFA/$1
	fi
	shift
done
