#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT [-X] [-l] name" >&2
	exit 1
}

while `dirname $0`/args $@; do
	case $1 in
	-X) X11=mount ;;
	-l) CLEAN=-l  ;;
	esac
	shift
done

NAME=$1
test "$NAME" != "" || usage

if test "$X11" = "mount"; then
	JAIL=/usr/local/jails/containers/$NAME
	X11=/.X11-unix

	xhost +local:$NAME
	mkdir -p $JAIL/tmp/$X11
	mount -t nullfs -o nocover /tmp/$X11 $JAIL/tmp/$X11
fi

jexec $CLEAN $NAME login -f root

test "$X11" != "" && umount $JAIL/tmp/$X11
