#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT [-Tc] name" >&2
	exit 1
}

TYPE=container

while `dirname $0`/args $@; do
	case $1 in
	--) shift; break  ;;
	-c) CONFIG=remove ;;
	-T) TYPE=template ;;
	esac
	shift
done

NAME=$1
test "$NAME" != "" || usage

CONTAINER=/usr/local/jails/"$TYPE"s/$NAME
if test -e $CONTAINER; then
	service jail onestop $NAME >/dev/null 2>&1
	jail -r $NAME >/dev/null 2>&1
	jail-umount-all $NAME

	DATASET=`zfs list $CONTAINER | grep "$CONTAINER" | awk '{print $1;}'`
	if test "$DATASET" != ""; then
		zfs destroy -r $DATASET
	else
		chflags -R 0 $CONTAINER/
		rm -rf $CONTAINER/
	fi
fi

test "$CONFIG" = "remove" && rm -f /etc/jail.conf.d/$NAME.conf
