#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT name" >&2
	exit 1
}

NAME=$1
test "$NAME" != "" || usage

CONTAINER=/usr/local/jails/containers/$NAME
X11=/tmp/.X11-unix

mkdir -p $CONTAINER/$X11
mount -t nullfs $X11 $CONTAINER/$X11
