#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT [-iu] [name | name base]" >&2
	exit 1
}

while `dirname $0`/args $@; do
	case $1 in
	-i) INTERACTIVE=on ;;
	-u) UPDATE=-u      ;;
	esac
	shift
done

NAME=$1
test "$NAME" != "" || NAME=linux

BASE=$2
test "$BASE" != "" || BASE=none

CONFIG=/etc/jail.conf.d/$NAME.conf
test -f "$CONFIG" || cat >$CONFIG <<EOF
$NAME {
	# STARTUP/LOGGING
	exec.start = "/bin/sh /etc/rc";
	exec.stop = "/bin/sh /etc/rc.shutdown";
	exec.consolelog = "/var/log/jail_console_\${name}.log";
	exec.clean;

	# HOSTNAME/PATH
	host.hostname = "\${name}";
	path = "/usr/local/jails/containers/\${name}";

	# NETWORK
	ip4 = inherit;
	interface = em0;

	# PERMISSIONS
	allow.mount;
	allow.mount.devfs;
	allow.mount.fdescfs;
	allow.mount.linprocfs;
	allow.mount.linsysfs;
	allow.mount.nullfs;
	allow.mount.tmpfs;
	allow.raw_sockets;
	enforce_statfs=1;

	# ENVIRONMENTS
	linux=new;

	# MOUNTS
	mount.devfs;
}
EOF

JAIL=/usr/local/jails/containers/$NAME
jail-create $NAME

mkdir -p $JAIL/tmp $JAIL/compat/linux/tmp
echo 'linux_enable="YES"' >$JAIL/etc/rc.conf

if test "$BASE" != "none" -o "$INTERACTIVE" = "on"; then
	service linux onestart >/dev/null

	jail -cm \
		name=$NAME \
		host.hostname="$NAME" \
		path="$JAIL" \
		interface="em0" \
		ip4=inherit \
		exec.start="/bin/sh /etc/rc" \
		exec.stop="/bin/sh /etc/rc.shutdown" \
		mount.devfs \
		devfs_ruleset=4 \
		allow.mount \
		allow.mount.devfs \
		allow.mount.fdescfs \
		allow.mount.procfs \
		allow.mount.linprocfs \
		allow.mount.linsysfs \
		allow.mount.tmpfs \
		enforce_statfs=1

	if test "$INTERACTIVE" = "on"; then
		jexec $NAME login -f root
	else
		case $BASE in
		noble)
			LINUX=$JAIL/compat/linux
			BASE=$JAIL/root/base.tar.gz
			fetch https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.3-base-amd64.tar.gz -o $BASE
			tar -xvzf $BASE -C $LINUX

			echo nameserver 8.8.8.8 >$LINUX/etc/resolv.conf
			printf "APT::Cache-Start 251658240;" >$LINUX/etc/apt/apt.conf.d/00aptitude

			FIX=$LINUX/root/bin/sh/apt-get-fix
			mkdir -p `dirname $FIX`
			cat >$FIX <<EOF
mv /var/lib/dpkg/info /var/lib/dpkg/info_silent
mkdir /var/lib/dpkg/info
apt-get update
apt-get -f install
mv /var/lib/dpkg/info/* /var/lib/dpkg/info_silent
rm -rf /var/lib/dpkg/info
mv /var/lib/dpkg/info_silent /var/lib/dpkg/info
apt-get update
apt-get upgrade
EOF
			chmod +x $FIX
			echo 'export PATH=$HOME/bin/sh:$PATH' >>$LINUX/root/.profile
			;;
		*)
			pkg -j $NAME install -y debootstrap
			jexec $NAME debootstrap $BASE /compat/linux
			;;
		esac
	fi

	service jail onestop $NAME >/dev/null
fi
