#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT name" >&2
	exit 1
}

while args $@; do
	case $1 in
	-X) X11=-X   ;;
	-l) CLEAN=-l ;;
	esac
	shift
done

NAME=$1
test "$NAME" != "" || usage

service jail onestart $NAME >/dev/null
jail-attach $X11 $CLEAN $NAME
service jail onestop $NAME >/dev/null
