#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT name" >&2
	exit 1
}


NAME=$1
test "$NAME" != "" || usage

service jail onestart $NAME >/dev/null && jexec $NAME login -f root && service jail onestop $NAME >/dev/null
