#!/bin/sh

PROJECT=`basename $0`

arg()
{
	test "$1" = "-X" && X11="-X"
	test "$1" = "-l" && CLEAN="-l"
}

usage()
{
	echo "usage: $PROJECT name" >&2
	exit 1
}

while echo -n "$1" | grep '^-' >/dev/null; do
	arg $1
	shift
done

NAME=$1
test "$NAME" != "" || usage

service jail onestart $NAME >/dev/null
jail-attach $X11 $CLEAN $NAME
service jail onestop $NAME >/dev/null
