#!/bin/sh

PROJECT=`basename $0`

arg()
{
	test "$1" = "--32" && ARCH="i386"
	test "$1" = "--64" && ARCH="amd64"
	test "$1" = "-666" && RULE="create"
	test "$1" = "-l32" && LIB32="install"
	test "$1" = "-t"   && TYPE="template"
	test "$1" = "-u"   && UPDATE="on"
	return 0
}

usage()
{
	echo "usage: $PROJECT [--32|--64] [-666] [-l32] [-tu] name" >&2
	exit 1
}

VERSION=`freebsd-version | sed 's/-p.*//'`
JAILS=/usr/local/jails
TYPE="container"
ARCH=`uname -p`

while echo -n "$1" | grep '^-' >/dev/null; do
	arg $1
	shift
done

NAME=$1
test "$NAME" != "" || usage

BASE=$JAILS/media/$ARCH/$VERSION-base.txz
if test ! -e $BASE; then
	mkdir -p $JAILS/media/$ARCH
	fetch https://download.freebsd.org/ftp/releases/$ARCH/$ARCH/$VERSION/base.txz -o $BASE
fi
if test "$LIB32" = "install" -a "$ARCH" = "amd64"; then
	LIB32=$JAILS/media/$ARCH/$VERSION-lib32.txz
	if test ! -e $LIB32; then
		mkdir -p $JAILS/media/$ARCH
		fetch https://download.freebsd.org/ftp/releases/$ARCH/$ARCH/$VERSION/lib32.txz -o $LIB32
	fi
fi

CONTAINER=$JAILS/"$TYPE"s/$NAME
if test ! -e $CONTAINER; then
	mkdir -p $CONTAINER
	tar -xf $BASE -C $CONTAINER
	test "$LIB32" != "" && tar -xf $LIB32 -C $CONTAINER
	cp /etc/resolv.conf $CONTAINER/etc/resolv.conf
	cp /etc/localtime $CONTAINER/etc/localtime
	cp /etc/machine-id $CONTAINER/etc/machine-id
fi

test "$UPDATE" = "on" -a "$ARCH" = "amd64" && freebsd-update -b $CONTAINER fetch install

CONFIG=/etc/jail.conf.d/$NAME.conf
TYPES="$TYPE"s
test -f $CONFIG || cat >$CONFIG <<EOF
$NAME {
	# STARTUP/LOGGING
	exec.start = "/bin/sh /etc/rc";
	exec.stop = "/bin/sh /etc/rc.shutdown";
	exec.consolelog = "/var/log/jail_console_\${name}.log";
	exec.clean;

	# HOSTNAME/PATH
	host.hostname = "\${name}";
	path = "$JAILS/$TYPES/\${name}";

	# NETWORK
	ip4 = inherit;
	interface = em0;

	# PERMISSIONS
	allow.raw_sockets;

	# MOUNTS
	mount.devfs;	
}
EOF

if test "$RULE" = "create"; then
	RULES=/etc/devfs.rules
	grep "devfsrules_unhide_jail=666" $RULES >/dev/null 2>&1 || cat >>$RULES <<EOF

[devfsrules_unhide_jail=666]
add unhide
EOF
fi
