#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT name" >&2
	exit 1
}

NAME=$1
test "$NAME" != "" || usage

umount-grep "/usr/local/jails/containers/$NAME" >/dev/null 2>&1
umount-grep "/usr/local/jails/containers/$NAME"
