#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT name" >&2
	exit 1
}

NAME=$1
CONTAINER=/usr/local/jails/containers/$NAME

test $NAME != "" || usage

test -d $CONTAINER || jail-create $NAME

service linux onestart >/dev/null 2>&1
service linux start >/dev/null 2>&1

jail -cm \
    name=$NAME \
    host.hostname="$NAME" \
    path="/usr/local/jails/containers/$NAME" \
    interface="em0" \
    ip4=inherit \
    exec.start="/bin/sh /etc/rc" \
    exec.stop="/bin/sh /etc/rc.shutdown" \
    mount.devfs \
    devfs_ruleset=4 \
    allow.mount \
    allow.mount.devfs \
    allow.mount.fdescfs \
    allow.mount.procfs \
    allow.mount.linprocfs \
    allow.mount.linsysfs \
    allow.mount.tmpfs \
    enforce_statfs=1

jexec $NAME su -

mkdir -p $CONTAINER/tmp/.X11-unix $CONTAINER/compat/$NAME/tmp/.X11-unix

service jail onestop $NAME
