#!/bin/sh

usage()
{
	echo "usage: linux name"
	exit 1
}

NAME=$1

test "$NAME" != "" || usage

service linux start >/dev/null 2>&1
service linux onestart >/dev/null 2>&1

service jail onestart $NAME >/dev/null 2>&1

jexec $NAME chroot /compat/$NAME /bin/bash

service jail onestop $NAME >/dev/null 2>&1
