#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT [name]" >&2
	exit 1
}

NAME=$1
test "$NAME" != "" || NAME="linux"
JAIL=/usr/local/jails/containers/$NAME

xhost +local:$NAME >/dev/null

service linux onestart >/dev/null
service jail onestart $NAME >/dev/null 2>&1
mount -t nullfs -o nocover /tmp $JAIL/compat/linux/tmp

jexec $NAME service linux start
jexec $NAME chroot /compat/linux login -f root

service jail onestop $NAME >/dev/null 2>&1
jail-umount-all $NAME
