#!/bin/sh

PWD=`pwd`
PROJECT=`basename $PWD`

test "$1" = "-r" && { R=true; shift; }

VERBOSITY=0
VERBOSITYFLAGS=""
while test "$1" = "-v"; do
	VERBOSITY=$((VERBOSITY+1))
	VERBOSITYFLAGS="$VERBOSITYFLAGS -v"
	shift
done

now()
{
	date +%s%N
}

run()
{
	if test $VERBOSITY -gt 1; then echo "$@"; fi
	"$@" || exit 1
}

printv()
{
	if test $VERBOSITY -gt 0; then echo "$@"; fi
}

ISPCFILES="lib"$PROJECT"ispc.[ah] lib"$PROJECT"ispc.so"
buildISPC()
{
	FILES=`ls *.ispc 2>/dev/null`
	if test "$FILES" != ""; then
		CGO_ENABLED=1; export CGO_ENABLED
		rm -f $ISPCFILES

		for file in $FILES; do
			BASE=`echo $file | cut -d '.' -f 1`
			FLAGS=--target=host

			TAG='^\/\/ispc:flags: '
			if sed 1q $file | grep $TAG >/dev/null; then
				FLAGS=`sed '1q' $file | sed "s/$TAG//"`
			fi
			run ispc $FLAGS $@ -o $BASE.o -h $BASE.h --pic $file
		done

		printv cat *.h
		cat *.h >lib"$PROJECT"ispc.h
		run rm -f `ls *.h | grep -v lib"$PROJECT"ispc`

		run ar rc lib"$PROJECT"ispc.a *.o
		run ld -o lib"$PROJECT"ispc.so -shared *.o
		run rm -f *.o
	fi
}

GOPATH=$HOME/go
case $GO in
1|10|103|1.0|1.0.3) GODIST=go1  ;;
  11|112|1.1|1.1.2) GODIST=go11 ;;
  12|122|1.2|1.2.2) GODIST=go12 ;;
  13|133|1.3|1.3.3) GODIST=go13 ;;
  14|143|1.4|1.4.3) GODIST=go14 ;;
  15|154|1.5|1.5.4) GODIST=go15 ;;
  16|164|1.6|1.6.4) GODIST=go16 ;;
                 *) GODIST=go   ;;
esac

GOROOT=$GOPATH/dist/$GODIST
PATH=$GOROOT/bin:$PATH; export PATH
export PATH GOPATH GOROOT

test "$CGO_ENABLED" = "" && { CGO_ENABLED=0; export CGO_ENABLED; }

# NOTE(anton2920): don't like Google spying on me.
GOPROXY=direct; export GOPROXY
GOSUMDB=off; export GOSUMDB

# Disable Go 1.11+ package management.
GO111MODULE=off; export GO111MODULE
#GOPATH=`go env GOPATH`:`pwd`; export GOPATH

case $GODIST in
go1|go11|go12|go13|go14)
	grep 'import "C"' *.go >/dev/null 2>&1 && RACE= || {
		test "`go env GOARCH`" = "386" && RACE= || {
			test "$GODIST" = "go14" && RACE=-race || RACE=
		}
	}
	DFLAGS=-gcflags='-N -l'
	MFLAGS=-gcflags='-m -m'
	#RFLAGS=-ldflags='-s -w'
	SFLAGS=-gcflags='-S'
	TCOUNT=""
	VET=""
	test "$GODIST" = "go14" && GCFLAGS="-pack  -complete -nolocalimports"
	test `go env GOARCH` = 386 && { GC=8g; LD=8l; } || { GC=6g; LD=6l; }
	;;
go15|go16)
	grep 'import "C"' *.go >/dev/null 2>&1 && RACE= || {
		test "`go env GOARCH`" = "386" && RACE= || RACE=-race
	}
	DFLAGS=-gcflags='-N -l'
	MFLAGS=-gcflags='-m -m'
	#RFLAGS=-ldflags='-s -w'
	SFLAGS=-gcflags='-S'
	TCOUNT=-test.count=8
	VET="go vet"
	GC=compile; LD=link
	;;
*)
	grep 'import "C"' *.go >/dev/null 2>&1 && RACE= || {
		test "`go env GOARCH`" = "386" && RACE= || RACE=-race
	}
	PGO="-pgo off"
	DFLAGS=-gcflags='all=-N -l'
	MFLAGS=-gcflags='all=-m -m'
	#RFLAGS=-ldflags='all=-s -w'
	SFLAGS=-gcflags='all=-S'
	TCOUNT=-test.count=8
	VET="go vet"
	GC=compile; LD=link
	;;
esac

case $GODIST in
go1|go11|go12|go13) GOFANOSTD=gofanostd13 ;;
              go14) GOFANOSTD=gofanostd14 ;;
              go15) GOFANOSTD=gofanostd15 ;;
              go16) GOFANOSTD=gofanostd16 ;;
                 *) GOFANOSTD=gofanostdxx ;;
esac

STARTTIME=`now`

TARGET=$1
shift

GPPTARGET=`grep -n gpp *.go? 2>/dev/null | cut -d ':' -f 1 | uniq | grep -v gpp`
#test "$GPPTARGET" != "" && run gpp -r

GOFA=github.com/anton2920/gofa
GOFILES=`echo *.go`

test "$R" = "" && go version
# test "$1" = "-std" && { GODEBUG=installgoroot=all go install std; shift; }

case $TARGET in
	'' | '-' | debug)
		CGO_ENABLED=1; export CGO_ENABLED
		run buildISPC -O0 -g
		run go build $VERBOSITYFLAGS -o $PROJECT $RACE $PGO "$DFLAGS" -tags gofadebug $@
		;;
	allocs | allocations)
		printv go build $VERBOSITYFLAGS -o /dev/null "$MFLAGS"
		go build $VERBOSITYFLAGS -o /dev/null "$MFLAGS" 2>&1 | sort | uniq | grep "moved to heap" >$PROJECT.esc
		;;
	allocs-plus | allocations-plus)
		printv go build $VERBOSITYFLAGS -o /dev/null "$MFLAGS"
		go build $VERBOSITYFLAGS -o /dev/null "$MFLAGS" 2>&1 | sort | uniq | grep "escapes to heap" | grep " in " >$PROJECT.esc
		;;
	clean)
		run rm -f *_gpp.go $PROJECT $PROJECT.[sS] $PROJECT.esc $PROJECT.test $PROJECT.test.esc c.out cpu.pprof mem.pprof $ISPCFILES
		run go clean -cache -modcache -testcache
		run rm -rf `go env GOCACHE`
		run rm -rf $GOPATH/pkg
		run rm -rf /tmp/cover*
		;;
	check)
		run $0 -r $VERBOSITYFLAGS test-race-cover
		run ./$PROJECT.test $@
		;;
	check-bench)
		run $0 -r $VERBOSITYFLAGS test
		run ./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. $@
		;;
	check-bench-cmp | check-bench-compare)
		run $0 -r check-bench "$TCOUNT" -test.bench=$1 | tee after

		git stash >/dev/null
		run $0 -r check-bench "$TCOUNT" -test.bench=$1 |tee before
		git stash pop >/dev/null

		OUTPUT=$PROJECT-diff.txt
		printv benchstat before after
		benchstat before after >$OUTPUT
		echo Results saved in $OUTPUT

		rm -f before after
		;;
	check-bench-cpu)
		run $0 -r $VERBOSITYFLAGS test

		OUTPUT=$PROJECT-cpu.pprof
		run ./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. -test.cpuprofile=$OUTPUT $@
		echo Results saved in $OUTPUT
		;;
	check-bench-mem)
		run $0 -r $VERBOSITYFLAGS test

		OUTPUT=$PROJECT-mem.pprof
		run ./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. -test.memprofile=$OUTPUT $@
		echo Results saved in $OUTPUT
		;;
	check-bench-tracing)
		run $0 -r $VERBOSITYFLAGS test-tracing
		run ./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. $@
		;;
	check-cover)
		run $0 -r $VERBOSITYFLAGS test-race-cover
		run ./$PROJECT.test -test.coverprofile=c.out

		OUTPUT=/tmp/coverage.html
		run go tool cover -html=c.out -o $OUTPUT
		echo Results saved in $OUTPUT

		run rm -f c.out
		;;
	check-msan)
		run $0 -r $VERBOSITYFLAGS test-msan
		run ./$PROJECT.test
		;;
	disas | disasm | disassembly)
		printv go build $VERBOSITYFLAGS -o /dev/null "$SFLAGS"
		go build $VERBOSITYFLAGS -o /dev/null "$SFLAGS" >$PROJECT.S 2>&1
		;;
	esc | escape | escape-analysis)
		printv go build $VERBOSITYFLAGS -o /dev/null "$MFLAGS"
		go build $VERBOSITYFLAGS -o /dev/null "$MFLAGS" >$PROJECT.esc 2>&1
		;;
	fmt)
		which goimports >/dev/null && run goimports -l -w *.go || run gofmt -l -s -w *.go
		;;
	msan)
		CGO_ENABLED=1; export CGO_ENABLED
		run buildISPC -O0 -g
		run go build $VERBOSITYFLAGS -o $PROJECT -msan $PGO "$DFLAGS" -tags gofadebug $@
		;;
	nostd)
		PKGPATH=$GOROOT/pkg/freebsd_amd64
		if test "$1" = "-a"; then
			run go install -tags gofanostd $@ $GOFA/...
			run go install -tags "gofanostd $GOFANOSTD"  -gcflags='-+' $@ $GOFA/nostd
		fi
		test -d $PKGPATH && run find $GOROOT/pkg/freebsd_amd64 -not -name '*.h' -delete
		run go tool $GC -o $PROJECT.a -p _`pwd` $GCFLAGS -I $GOPATH/pkg/freebsd_amd64 $GOFILES
		run go tool $LD -o $PROJECT -s -w -L $GOPATH/pkg/freebsd_amd64 $PROJECT.a
		run rm -f $PROJECT.a
		;;
	objdump)
		printv go tool objdump $@ $PROJECT
		go tool objdump $@ $PROJECT >$PROJECT.s
		;;
	pgo)
		run $0 -r $VERBOSITYFLAGS test

		printv ./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. -test.count=8 -test.cpuprofile=$PROJECT-cpu.pprof
		./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. -test.count=8 -test.cpuprofile=$PROJECT-cpu.pprof | tee before

		run go test $VERBOSITYFLAGS -c -o $PROJECT.test -pgo=$PROJECT-cpu.pprof -vet=off

		printv ./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. -test.count=10 -test.cpuprofile=tmp.pprof
		./$PROJECT.test -test.run=^Benchmark -test.benchmem -test.bench=. -test.count=10 -test.cpuprofile=tmp.pprof | tee after

		OUTPUT=$PROJECT-diff.txt
		printv benchstat before after
		benchstat before after >$OUTPUT
		echo Results saved in $OUTPUT

		run rm before after tmp.pprof
		;;
	png)
		OUTPUT=/tmp/cpu.png
		run go tool pprof -png $PROJECT-cpu.pprof >$OUTPUT
		echo Results saved in $OUTPUT
		;;
	profiling)
		run go build $VERBOSITYFLAGS -o $PROJECT -ldflags="-X main.BuildMode=Profiling"
		;;
	release)
		run buildISPC -O3
		run go build $VERBOSITYFLAGS -o $PROJECT "$RFLAGS" $@
		;;
	release-unsafe)
		run buildISPC -O3
		if test "$GO14" = "true"; then
			run go build $VERBOSITYFLAGS -o $PROJECT -gcflags="-B"
		else
			run go build $VERBOSITYFLAGS -o $PROJECT -gcflags="all=-B"
		fi
		;;
	test)
		run buildISPC -O3
		run $0 -r $VERBOSITYFLAGS vet
		run go test $VERBOSITYFLAGS -c -o $PROJECT.test -vet=off
		;;
	test-msan)
		CGO_ENABLED=1; export CGO_ENABLED
		run buildISPC -O0
		run $0 -r $VERBOSITYFLAGS vet
		run go test $VERBOSITYFLAGS -c -o $PROJECT.test -vet=off -msan $PGO "$DFLAGS" -tags gofadebug
		;;
	test-race-cover)
		CGO_ENABLED=1; export CGO_ENABLED
		run buildISPC -O0 -g
		run $0 -r $VERBOSITYFLAGS vet
		run go test $VERBOSITYFLAGS -c -o $PROJECT.test -vet=off $RACE $PGO "$DFLAGS" -cover -tags gofadebug
		;;
	test-tracing)
		run buildISPC -O3
		run $0 -r $VERBOSITYFLAGS vet
		run go test $VERBOSITYFLAGS -c -o $PROJECT.test -vet=off -tags gofatrace
		;;
	tracing)
		run buildISPC -O3
		run go build $VERBOSITYFLAGS -o $PROJECT -tags gofatrace $@
		;;
	vet)
		# run go vet $VERBOSITYFLAGS -unsafeptr=false
		run $VET $VERBOSITYFLAGS
		;;
	*)
		printf "Target '%s' is not supported!\n" $TARGET >&2
		exit 1
		;;
esac

ENDTIME=`now`
ELAPSEDMS=`echo "scale=2; ($ENDTIME-$STARTTIME)/1000000" | bc`

echo Done $TARGET in "$ELAPSEDMS"ms
