#!/bin/sh

IP=`ifconfig | grep inet | awk '{print $2;}' | sed 1q`

SOCKS=6585
ZHTTP=3128
ZSOCK=1080

ssh -D $IP:$SOCKS -L $IP:$ZHTTP:127.0.0.1:$ZHTTP -L $IP:$ZSOCK:127.0.0.1:$ZSOCK proxy.anton2920.ru -N -C
