#!/bin/sh

toggle()
{	
	DEV="$1"

	xinput --list-props "$DEV" | grep '.*libinput Scroll Method Enabled (.*1$' && VALUE="0, 0, 0" || VALUE="0, 0, 1"
	xinput --set-prop "$DEV" 'libinput Scroll Method Enabled' $VALUE
}

MOUSE="Logitech Optical USB Mouse"
TRACK="Generic PS/2 mouse"

toggle "$MOUSE"
toggle "$TRACK"
