#!/bin/sh

xinput --list-props 'Logitech Optical USB Mouse' | grep '.*libinput Scroll Method Enabled (.*1$'
if [ $? -eq 0 ] ; then
	xinput --set-prop 'Logitech Optical USB Mouse' 'libinput Scroll Method Enabled' 0, 0, 0
else
	xinput --set-prop 'Logitech Optical USB Mouse' 'libinput Scroll Method Enabled' 0, 0, 1
fi

