#!/bin/sh

case `hostname` in
	anton-FBSD)
		# Volume for headphones.
		mixer vol 90
		mixer pcm 100
		mixer mic 100
		
		# Volume for recording from second PC.
		mixer -f /dev/mixer4 mic 30
		mixer -f /dev/mixer4 line 50
		mixer -f /dev/mixer4 igain 50
		mixer -f /dev/mixer4 ogain 50
		mixer -f /dev/mixer4 mix 100
		
		# Constraining Wacom to the right monitor.
		xinput map-to-output 'Wacom Graphire4 4x5 Pen stylus' DVI-D-0
		xinput map-to-output 'Wacom Graphire4 4x5 Pad pad' DVI-D-0
		xinput map-to-output 'Wacom Graphire4 4x5 Pen eraser' DVI-D-0
		xinput map-to-output 'Wacom Graphire4 4x5 Pen cursor' DVI-D-0
		;;
	anton-DELL)
		;;
	anton-TFBSD)
		mixer vol=0.7
		mixer pcm=0.5

		xinput set-prop 10 "libinput Tapping Enabled" 1
		xinput set-prop 10 "libinput Tapping Drag Lock Enabled" 1
		;;
esac
