#!/bin/sh

case `hostname` in
	anton-ASUS)
		mixer vol 80
		mixer rec 90
		mixer mic 100
		
		xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1
		xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Drag Lock Enabled' 1
		xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Accel Speed' 0.3
		;;
	anton-DELL)
		# Volume for headphones.
		mixer vol=0.9
		mixer pcm=1.0

		xinput --set-prop 'DELL0740:00 06CB:7E7E TouchPad' 'libinput Tapping Enabled' 1
		xinput --set-prop 'DELL0740:00 06CB:7E7E TouchPad' 'libinput Tapping Drag Lock Enabled' 1
		;;
	anton-FBSD)
		# Volume for headphones.
		mixer vol=0.95
		mixer pcm=1
		mixer mic=1

		# Volume for recording from second PC.
		mixer -f /dev/mixer4 mic=0.3
		mixer -f /dev/mixer4 line=0.5
		mixer -f /dev/mixer4 igain=0.5
		mixer -f /dev/mixer4 ogain=0.5
		mixer -f /dev/mixer4 mix=1

		# Constraining Wacom to the right monitor.
		xinput map-to-output 'Wacom Graphire4 4x5 Pen stylus' DVI-D-0
		xinput map-to-output 'Wacom Graphire4 4x5 Pad pad' DVI-D-0
		xinput map-to-output 'Wacom Graphire4 4x5 Pen eraser' DVI-D-0
		xinput map-to-output 'Wacom Graphire4 4x5 Pen cursor' DVI-D-0
		;;
	anton-TFBSD)
		mixer vol=0.7
		mixer pcm=0.5

		xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
		xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Drag Lock Enabled' 1
		;;
esac
