#!/bin/sh

arg()
{
	test "$1" = "-i" && INTERACTIVE="yes"
	return 0
}

usage()
{
	echo "usage: $PROJECT [-i] [name]" >&2
	exit 1
}

while echo -n "$1" | grep '^-' >/dev/null; do
	arg $1
	shift
done

NAME=$1
test "$NAME" != "" || NAME=steam

JAIL=/usr/local/jails/containers/$NAME

kldload nullfs >/dev/null 2>&1
sysctl security.bsd.unprivileged_chroot=1 >/dev/null
sysctl vfs.usermount=1 >/dev/null

xhost +local:$NAME >/dev/null
service linux onestart >/dev/null
service jail onestart $NAME >/dev/null 2>&1

mount -t nullfs /tmp $JAIL/tmp
mount -t nullfs $JAIL/root $JAIL/home/root
rm -rf /tmp/dumps

service -j $NAME linux start

if test "$INTERACTIVE" = "yes"; then
	jexec $NAME login -f root
else
	jexec $NAME /bin/sh -c "export HOME=/home/root; export DISPLAY=:0; /usr/local/steam-utils/bin/steam"
fi

service jail onestop $NAME >/dev/null 2>&1
jail-umount-all $NAME
