#!/bin/sh

PROJECT=`basename $0`

usage()
{
	echo "usage: $PROJECT [-i] [name]" >&2
	exit 1
}

while `dirname $0`/args $@; do
	case $1 in
	-i) INTERACTIVE="yes" ;;
	 *) usage             ;;
	esac
	shift
done

NAME=$1
test "$NAME" != "" || NAME=steam

JAIL=/usr/local/jails/containers/$NAME

kldload nullfs >/dev/null 2>&1
sysctl security.bsd.unprivileged_chroot=1 >/dev/null
sysctl compat.linux.use_real_ifnames=1 >/dev/null
sysctl vfs.usermount=1 >/dev/null

xhost +local:$NAME >/dev/null
service linux onestart >/dev/null
service jail onestart $NAME >/dev/null 2>&1

mount -t nullfs /tmp $JAIL/tmp
mount -t nullfs $JAIL/root $JAIL/home/root
rm -rf /tmp/dumps

service -j $NAME linux start

if test "$INTERACTIVE" = "yes"; then
	jexec $NAME login -f root
else
	jexec $NAME /bin/sh -c "export HOME=/home/root; export DISPLAY=:0; /home/root/bin/steam-launch"
fi

service jail onestop $NAME >/dev/null 2>&1
`dirname $0`/jail-umount-all $NAME
