#!/bin/sh

set -e

if test ! "`kldstat | grep vmm`"; then
	kldload vmm
	sysctl net.link.tap.up_on_open=1
	ifconfig tap0 create
	ifconfig bridge0 create
	ifconfig bridge0 addm em0 addm tap0
	ifconfig bridge0 up
fi
